
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int READ = 16;
  public static final int MULTIPLY = 25;
  public static final int FLAG = 12;
  public static final int QUESTION = 31;
  public static final int PLUS = 23;
  public static final int RPAREN = 8;
  public static final int CALL = 18;
  public static final int IN = 5;
  public static final int UP = 28;
  public static final int END = 3;
  public static final int LPAREN = 7;
  public static final int COLON = 9;
  public static final int WRITE = 17;
  public static final int ID = 4;
  public static final int DO = 20;
  public static final int SMILE = 14;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int NUMBER = 10;
  public static final int DIVIDE = 26;
  public static final int FLIP = 30;
  public static final int WHEN = 19;
  public static final int MAIN = 13;
  public static final int STRINGLIT = 27;
  public static final int MINUS = 24;
  public static final int error = 1;
  public static final int NUMBERLIT = 22;
  public static final int ASSIGN = 15;
  public static final int DOWN = 29;
  public static final int START = 2;
  public static final int OUT = 6;
  public static final int DONE = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "START",
  "END",
  "ID",
  "IN",
  "OUT",
  "LPAREN",
  "RPAREN",
  "COLON",
  "NUMBER",
  "STRING",
  "FLAG",
  "MAIN",
  "SMILE",
  "ASSIGN",
  "READ",
  "WRITE",
  "CALL",
  "WHEN",
  "DO",
  "DONE",
  "NUMBERLIT",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "STRINGLIT",
  "UP",
  "DOWN",
  "FLIP",
  "QUESTION"
  };
}

